### ISSUE TITLE
Listening to a Websocket Server?

### ISSUE THREAD

**Issue by jedimdan** [Textalk/websocket-php#44] opened 2017-01-31 14:09 UTC
Hi there! I'm trying to build a client that will listen to a Websocket server and respond when the server sends an event. I tried doing this (not sure if it's the correct way to do it)

```php
$client = new Client('ws://<server>');
while (1) {
            $message = $client->receive();
            if ($message) {
                $messageObject = json_decode($message);
                //do something, such as print to console
            }
}
```

But it would miss messages sometimes and after about ten minutes of inactivity from the server, it would die with this error:

```
[WebSocket\ConnectionException]                                                                                                                 
  Empty read; connection dead?  Stream state: {"timed_out":true,"blocked":true,"eof":false,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_b  
  ytes":0,"seekable":false}
```

Am I doing this incorrectly?

Thanks in advance

**Comment by szado** [comment] 2017-02-25 21:55
I have the same problem, any suggestions?

**Comment by l0rb** [comment] 2017-03-21 19:47
+1 getting the " Empty read; connection dead?" error pretty often, usually within less them 1 minute

**Comment by materkov** [comment] 2017-06-01 07:16
I think you should take a look at 'timeout' option in Client.

**Comment by kensoh** [comment] 2017-07-17 09:38
I'm interested in this issue and wonder if Daniel has found a solution? The default timeout is 5, I'm thinking isn't this reasonable with enough buffer time for modern client to server communication, or would it be recommended to double it to 10 and if there are any downsides to doing so.

**Comment by jedimdan** [comment] 2017-07-18 01:28
@kensoh I'm afraid I gave up. My work around was to write a simple 1 file node app in javascript (it's so much easier to get a WebSockets client working in JS than in PHP) that subscribes to a server and passes the content over to the PHP app to do the rest by executing a command.

**Comment by kensoh** [comment] 2017-07-18 06:29
@jedimdan I see.. oh yes, it is in-built into JavaScript and only takes few lines to code to send and receive the message. That sounds like a cool way to implement, thanks for sharing :)

For my use case, I need concurrency, in the sense I need to be able to receive events during execution of a JavaScript function. That is not possible with single-threaded JS unless I use async/await or promises, which are not yet supported by the underlying tool that my project is based on. So my other reasonable choice is to implement it as a separate PHP thread and then pass the data to my JS code for processing (through simple I/O files on the local file system).

**Comment by kensoh** [comment] 2017-07-18 06:32
Also want to add that it is not because PHP is a lousy language. It is because PHP is designed primarily for use on server side for content generation, while JavaScript was originally designed to be used on client side for content consumption. To implement a websocket client to consume and send websocket messages I guess is not really the goal of PHP language, so it is not built into the language.

**Comment by rabashani** [comment] 2018-02-15 10:03
I am getting the same error 

Empty read; connection dead?  Stream state: {"crypto":{"protocol":"TLSv1.2","cipher_name":"ECDHE-RSA-AES128-GCM-SHA256","cipher_bits":128,"cipher_version":"TLSv1\/SSLv3"},"timed_out":false,"blocked":true,"eof":true,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false}


did anyone solve this? @kensoh 
or someone can share a different solution 
@jedimdan can you share your solution?

**Comment by kensoh** [comment] 2018-02-15 17:12
For my use case it is straightforward. After sending I just keep looping to read the response. Thus no error. The websocket server in my use case is Chrome. Below is snippet of the full source code for https://github.com/tebelorg/TagUI/blob/master/src/tagui_chrome.php

```php
$client->send($tagui_intent); $intent_result_string = ""; // keep reading until chrome replies with message
while ($intent_result_string == "") {try {$intent_result_string = trim($client->receive());} catch (Exception $e) {}}
```

**Comment by ryancwalsh** [comment] 2019-03-09 17:16
This worked out better for me: https://github.com/ratchetphp/Ratchet/issues/627#issuecomment-471185647

**Comment by Chevil5** [comment] 2019-04-26 08:57
I have the same problem. Did anyone fix it?

**Comment by sirn-se** [comment] 2020-05-17 16:41
The `"timed_out": true` implies that the stream has been closed by server because of its time out setting. The client is expected to throw exception on failed send/receive operations, no matter the cause.

In the example code above, it's easily fixed by putting the `$message = $client->receive()` inside a try/catch clause. On the next while iteration, it will reconnect and continue reading.

**Comment by sirn-se** [comment] 2020-06-07 12:21
Current documentation explains how to perform an error safe listener using try/catch and loop. Closing this issue.

**Closed by sirn-se** 2020-06-07 12:21 UTC
