### ISSUE TITLE
Again, «Empty read; connection dead? ...»

### ISSUE THREAD

**Issue by evikza** [Textalk/websocket-php#84] opened 2020-06-09 19:56 UTC
Hello. Can you help me, plz? 😰 

```console
PHP 7.3.2,
textalk 1.3.1
```

```php
<?php

// ini_set('max_execution_time', 0);

require 'vendor/autoload.php';
require 'variables.php';

use GuzzleHttp\Client;
use WebSocket\Client as WebSocket;

$client = new GuzzleHttp\Client();
$res = $client->request('GET', $base_uri . 'user/oauth', [
  'verify' => false,
  'headers' => [
    'Authorization' => 'Bearer ' . $user_token,
  ],
]);

if ($res->getStatusCode() === 200) {
  $respObjDecoder = json_decode($res->getBody(), 0)->data;

  $clientWebSoket = new WebSocket(
    'wss://centrifugo.donationalerts.com/connection/websocket'
  );

  $clientWebSoket->send(
    '{"params": {"token": "' .
      $respObjDecoder->socket_connection_token .
      '"},"id": ' .
      $respObjDecoder->id .
      '}'
  );

  $respObjDecoderMessage = json_decode($clientWebSoket->receive(), 0)->result
    ->client;

  $arrayToPrep = [
    'channels' => ['$alerts:donation_' . $respObjDecoder->id],
    'client' => $respObjDecoderMessage,
  ];

  $res = $client->request('POST', $base_uri . 'centrifuge/subscribe', [
    'verify' => false,
    'json' => $arrayToPrep,
    'headers' => [
      'Authorization' => 'Bearer ' . $user_token,
    ],
  ]);

  $respObjChannels = json_decode($res->getBody(), 0)->channels[0];

  $clientWebSoket->send(
    '{"params": {
        "channel": "' .
      $respObjChannels->channel .
      '",
        "token": "' .
      $respObjChannels->token .
      '" },
    	"method": 1,
    	"id": 2
}'
  );

  # start to listening ¯\_(ツ)_/¯

  while (true) {
    try {
      $message = $clientWebSoket->receive();
      echo $message;
    } catch (\WebSocket\ConnectionException $e) {
      echo $e;
    }
  }
  $clientWebSoket->close();
}
```

I get a response from the server:

```console
{"id":2,"result":{"recoverable":true,"seq":11,"epoch":"1589467947"}}
{"result":{"type":1,"channel":"$alerts:donation_424675","data":{"info":{"user":"820","client":"21434006-8483-4f96-870u-92c0c7cea1ff"}}}}
```

Then,

```php
WebSocket\ConnectionException: Empty read; connection dead?  Stream state: {"crypto":{"protocol":"TLSv1.2","cipher_name":"ECDHE-RSA-AES256-GCM-SHA384","cipher_bits":256,"cipher_version":"TLSv1.2"},"timed_out":true,"blocked":true,"eof":false,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false} in C:\OServer\domains\alerts\vendor\textalk\websocket\lib\Base.php:298
Stack trace:
#0 C:\OServer\domains\alerts\vendor\textalk\websocket\lib\Base.php(159): WebSocket\Base->read(2)
#1 C:\OServer\domains\alerts\vendor\textalk\websocket\lib\Base.php(149): WebSocket\Base->receiveFragment()
#2 C:\OServer\domains\alerts\index.php(69): WebSocket\Base->receive()
#3 {main}
```

If I turn off error output:

```php
catch (\WebSocket\ConnectionException $e) { }
```

Result in console:

```php
{"id":2,"result":{"recoverable":true,"seq":11,"epoch":"1589467947"}}
{"result":{"type":1,"channel":"$alerts:donation_424675","data":{"info":{"user":"820","client":"21434006-8483-4f96-870u-92c0c7cea1ff"}}}}
ping
```

Sorry for my bad English 😶

**Comment by Fenslau** [comment] 2020-09-15 16:23
Hello, I have 
`Fatal error: Uncaught WebSocket\ConnectionException: Empty read; connection dead?  Stream state: {"crypto":{"protocol":"TLSv1.2","cipher_name":"ECDHE-ECDSA-AES128-GCM-SHA256","cipher_bits":128,"cipher_version":"TLSv1.2"},"**timed_out":false**,"blocked":true,"eof":true,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false} in /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php:340
Stack trace:
#0 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(320): WebSocket\Base->throwException('Empty read; con...')
#1 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(175): WebSocket\Base->read(2)
#2 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(164): WebSocket\Base->receiveFragment()
#3 /var/www/sphere/data/www/sphere-market.ru/vktoppost/stream/stream.php(22): WebSocket\Base->receive()
#4 {main}
  thrown in /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php on line 340`
often enough.
And there is not time-out. 
People who have server say that the problem is not on their side.
Nobody knows what to do =(

**Comment by sirn-se** [comment] 2020-11-07 11:51
Possibly the same issue as in https://github.com/Textalk/websocket-php/issues/104

That is, the stream is there but not usable. So the client doesn't realize it need to re-connect.

**Comment by Fenslau** [comment] 2020-11-10 18:54
> Possibly the same issue as in #104
> 
> That is, the stream is there but not usable. So the client doesn't realize it need to re-connect.

I have to say that my stream is not dead after such a exception. 
So, I have one and after that all is ok (for a while) until next exception, that could happens after next 1000 - 8000 messages....

**Comment by sirn-se** [comment] 2020-11-11 16:04
> I have to say that my stream is not dead after such a exception.
> So, I have one and after that all is ok (for a while) until next exception, that could happens after next 1000 - 8000 messages....

Well, it looks like the read function expects more data to read byt the stream I empty. By your dump it's impossible to say if that is caused by client, server or a network glitch.

**Comment by Fenslau** [comment] 2020-11-13 08:59
> > I have to say that my stream is not dead after such a exception.
> > So, I have one and after that all is ok (for a while) until next exception, that could happens after next 1000 - 8000 messages....
> 
> Well, it looks like the read function expects more data to read but the stream I empty. By your dump it's impossible to say if that is caused by client, server or a network glitch.
Here is my log:
[debug] Received 'ping', sending 'pong'. 
[debug] Wrote 6 of 6 bytes. 
[info] Sent 'pong' message 
[info] Received 'ping' message 
[error] Empty read; connection dead? 

WebSocket\ConnectionException: Empty read; connection dead?  Stream state: {"crypto":{"protocol":"TLSv1.2","cipher_name":"ECDHE-ECDSA-AES128-GCM-SHA256","cipher_bits":128,"cipher_version":"TLSv1.2"},"timed_out":false,"blocked":true,"eof":true,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false} in /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php:340
Stack trace:
#0 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(320): WebSocket\Base->throwException('Empty read; con...')
#1 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(175): WebSocket\Base->read(2)
#2 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(164): WebSocket\Base->receiveFragment()
#3 /var/www/sphere/data/www/sphere-market.ru/vktoppost/stream/stream.php(48): WebSocket\Base->receive()
#4 {main}
[debug] Wrote 244 of 244 bytes. 
[info] Client connected to to wss://streaming.vk.com/stream?key=f7ac9eefef5c6c9183add5936e9593cc8292e11d 
[info] Received 'text' message 
[info] Received 'text' message 
[info] Received 'text' message 

I do reconnect after exception... But I didn't it earlier.
So, it seems to be that there is not any terrible situation, but I try to understand - why it happens.

**Comment by Fenslau** [comment] 2020-11-18 03:40
I have once more dump:

`[info] Received 'text' message 
[debug] Received 'ping', sending 'pong'. 
[debug] Wrote 6 of 6 bytes. 
[info] Sent 'pong' message 
[info] Received 'ping' message 
[error] Empty read; connection dead? 

WebSocket\ConnectionException: Empty read; connection dead?  Stream state: {"crypto":{"protocol":"TLSv1.2","cipher_name":"ECDHE-ECDSA-AES128-GCM-SHA256","cipher_bits":128,"cipher_version":"TLSv1.2"},"timed_out":false,"blocked":true,"eof":true,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false} in /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php:340
Stack trace:
#0 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(320): WebSocket\Base->throwException('Empty read; con...')
#1 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(175): WebSocket\Base->read(2)
#2 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(164): WebSocket\Base->receiveFragment()
#3 /var/www/sphere/data/www/sphere-market.ru/vktoppost/stream/stream.php(48): WebSocket\Base->receive()
#4 {main}[debug] Wrote 12 of 12 bytes. 
[info] Sent 'close' message 
[debug] Closing with status: 讠(ETXxE8).
[error] Empty read; connection dead? 

Fatal error: Uncaught WebSocket\ConnectionException: Empty read; connection dead?  Stream state: {"crypto":{"protocol":"TLSv1.2","cipher_name":"ECDHE-ECDSA-AES128-GCM-SHA256","cipher_bits":128,"cipher_version":"TLSv1.2"},"timed_out":false,"blocked":true,"eof":true,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false} in /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php:340
Stack trace:
#0 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(320): WebSocket\Base->throwException('Empty read; con...')
#1 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(175): WebSocket\Base->read(2)
#2 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(164): WebSocket\Base->receiveFragment()
#3 /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php(291): WebSocket\Base->receive()
 in /var/www/sphere/data/www/sphere-market.ru/vktoppost/Websocket/vendor/textalk/websocket/lib/Base.php on line 340
[debug] Wrote 244 of 244 bytes. 
[info] Client connected to to wss://streaming.vk.com/stream?key=f234a7b949aa806f94a7efacb72aa9d39c3370e7 
[info] Received 'text' message `

here are 2 exceptions one by one... And the last is Uncaught..... why???
my code:
`main_cycle:
$db = new SafeMysql(array('host' => 'localhost', 'user' => '***', 'pass' => '***','db' => '***', 'charset' => 'utf8mb4'));
		$info = $db->getRow("SELECT * FROM stream");
		$endpoint = $info['endpoint'];
		$key = $info['streamkey'];		

	$option = array (
		'timeout' => 160
	);
	$url = "wss://$endpoint/stream?key=$key";
	
	$client = new Client($url, $option);
	$client->setLogger(new EchoLog());
try { 
cycle:
	$info=$client->receive();
	$info=json_decode ($info, true);
// do smthg....
goto cycle;
} catch (\WebSocket\ConnectionException $e) {
        echo "\n".$e;
		$client->close();
		goto main_cycle;
}`

**Comment by sirn-se** [comment] 2020-11-18 07:53
Because it occurs on `$client->close()`, in the catch clause.

Same state as before, the stream is there but not available for reading.

**Closed** 2020-11-23 21:21 UTC

**Comment by jasonz1987** [comment] 2020-12-04 10:53
i got same error when use the client


```
 #message: "stream_get_meta_data(): supplied resource is not a valid stream resource"
  #code: 0
  #file: "./vendor/textalk/websocket/lib/Base.php"
  #line: 341
  #severity: E_WARNING
  trace: {
    ./vendor/textalk/websocket/lib/Base.php:341 { …}
    Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() {}
    ./vendor/textalk/websocket/lib/Base.php:341 { …}
    ./vendor/textalk/websocket/lib/Base.php:328 { …}
    ./vendor/textalk/websocket/lib/Base.php:177 { …}
    ./vendor/textalk/websocket/lib/Base.php:166 { …}
    ./app/Processes/PriceProcess.php:62 {
      App\Processes\PriceProcess::callback(Server $swoole, Process $process)^
      › 
      › $huobiData = gzdecode($huobiClient->receive());
      › 
    }
    App\Processes\PriceProcess::callback() {}
    ./vendor/hhxsv5/laravel-s/src/Illuminate/LogTrait.php:82 { …}
    ./vendor/hhxsv5/laravel-s/src/Swoole/Process/CustomProcessTrait.php:64 { …}
  }
}
```

```
stream resource {@709
  crypto: array:4 [
    "protocol" => "TLSv1.3"
    "cipher_name" => "TLS_AES_256_GCM_SHA384"
    "cipher_bits" => 256
    "cipher_version" => "TLSv1.3"
  ]
  timed_out: true
  eof: false
  blocked: true
  stream_type: "tcp_socket/coroutine"
  mode: "r+"
  unread_bytes: 0
  seekable: false
  options: []
}
```

**Comment by sirn-se** [comment] 2020-12-04 11:45
@jasonz1987 

It's not the same error as referred to earlier in this issue.

The error you get is because the code attempts to retrieve metadata from a stream that have been closed. This can happen if a stream has unexpectedly closed while attempting to read or write on it.

This issue is actually fixed in `master` branch, but for some reason I never pushed a new version. I will fix that during the weekend.

**Comment by sirn-se** [comment] 2020-12-04 21:40
https://github.com/Textalk/websocket-php/pull/120
